{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redpillanalytics",
    "module": "simple-build",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "eeskrxbcpna2xk6hte6fw3quw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "simple-build-1.0.0.jar",
          "url": "simple-build-1.0.0.jar",
          "size": 2013,
          "sha512": "469c9d60d70c340ecc013c1508151f811c542d7f3ff5b66da18a78aa6a40e55fa8b8a55a09ca57b918c1c296ac3c90fea0e59103c1b6bbfd4a1b6e3bce8aa059",
          "sha256": "004d138c33198b2746d3088247b4c89ec2db0091bd8be24af27a650fe7c1ebad",
          "sha1": "c8fc6712dd8161474ca457563f82d26e3af60887",
          "md5": "e47a7afc22469f6cc2c2a3b501ced100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "simple-build-1.0.0.jar",
          "url": "simple-build-1.0.0.jar",
          "size": 2013,
          "sha512": "469c9d60d70c340ecc013c1508151f811c542d7f3ff5b66da18a78aa6a40e55fa8b8a55a09ca57b918c1c296ac3c90fea0e59103c1b6bbfd4a1b6e3bce8aa059",
          "sha256": "004d138c33198b2746d3088247b4c89ec2db0091bd8be24af27a650fe7c1ebad",
          "sha1": "c8fc6712dd8161474ca457563f82d26e3af60887",
          "md5": "e47a7afc22469f6cc2c2a3b501ced100"
        }
      ]
    }
  ]
}
