{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redpillanalytics",
    "module": "simple-build",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "5ot527miindydey4kkhxlba3tu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "simple-build-1.0.0.jar",
          "url": "simple-build-1.0.0.jar",
          "size": 2013,
          "sha512": "4fdbda15478e5f76b98f5b780c9eb3d2266a5cdce225390c53ee15171a80179b58270d52490280174792e38ce71d7b79351bc715a48cb0c713852f851425e7fb",
          "sha256": "4863ea88798034271dbf67e60f84558428ba487b7dcf26945dd439ee8c7e1a63",
          "sha1": "0997cd66152cf25d57c09dd41c27da0fee17ffba",
          "md5": "ca3230a9c96e695411e35131f2535a77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "simple-build-1.0.0.jar",
          "url": "simple-build-1.0.0.jar",
          "size": 2013,
          "sha512": "4fdbda15478e5f76b98f5b780c9eb3d2266a5cdce225390c53ee15171a80179b58270d52490280174792e38ce71d7b79351bc715a48cb0c713852f851425e7fb",
          "sha256": "4863ea88798034271dbf67e60f84558428ba487b7dcf26945dd439ee8c7e1a63",
          "sha1": "0997cd66152cf25d57c09dd41c27da0fee17ffba",
          "md5": "ca3230a9c96e695411e35131f2535a77"
        }
      ]
    }
  ]
}
